language: node_js
os: windows
cache:
    directories:
        - ~/.npm
node_js:
    - '12'
git:
    depth: 3
script:
    - yarn build

before_deploy:
  - cd $TRAVIS_BUILD_DIR

repo: AlejandroPerez1992/Spa-Babel-Webpack

github_url: https://github.com/AlejandroPerez1992/Spa-Babel-Webpack
deploy:
    provider: pages
    edge: true,
    skip-cleanup: true
    keep-history: true
    local-dir: Rp4/
    github-token: $GITHUB_TOKEN
    target-branch: gh-pages
    commit_message: "Deploy Release"
    on:
        branch: master